### ISSUE TITLE
Error when all agents die

### ISSUE THREAD

**Issue by Erickson400** [pastra98/NEAT_for_Godot#10]
I'm getting the error break point from ga.gd line 359 when ever all agents die.
New generations are created normally if i use a key press or something that's not checking if all agents are dead.

**Comment by pastra98** [comment]
Hi, your issue is a little unclear, but I assume it has to do with `total_adjusted_species_avg_fitness` being 0. Have you checked there yet?

If all your agents have 0 fitness, the selection becomes ineffective. You can circumvent this by assigning a base-rate fitness value of e.g. 1.

**Comment by Erickson400** [comment]
That did it, weird, i though it generated agents from the fitness after the simulation, not the default 0 value i set the variable to.

**Comment by Erickson400** [comment]
oh, also i was not resetting the environment's settings so it was actually colliding with a kill trigger even though they had no chance of getting fitness.
