### ISSUE TITLE
Game freezes when creating a new GA

### ISSUE THREAD

**Issue by Erickson400** [pastra98/NEAT_for_Godot#9]
I'm following the documentation and i'm at the part where i have to populate the game with agents.
But it freezes when i call the function (as in var ga = GeneticAlgorithm.new(2, 1, AGENT_BODY_PATH, false, "dino_params")

**Comment by Erickson400** [comment]
It seems to be an infinite loop on line 129 of ga.gd

**Comment by Erickson400** [comment]
ok i found out i cant have less than 2 outputs. if i put 1 output only then its going to freeze

**Comment by pastra98** [comment]
Hi, that's interesting. I don't see why 1 output should cause issues...
Check out the [GA constructor in the XOR demo](https://github.com/pastra98/NEAT_for_Godot/blob/master/src/demos/xor/xor_main.gd#L21), it has pretty much the same setup as your Dino game.

My guess would be that your number of initial links is > 2. In the Xor config, [it is set to 2](https://github.com/pastra98/NEAT_for_Godot/blob/master/src/demos/xor/xor_params.cfg#L8).

It will try to create at least as many links as you specify in the config, but each link can only connect 2 unique nodes. In a setup with 2 inputs and 1 output, there's just two possibilities.

Let me know if thats your issue, I should add that to the wiki, or implement a check for this in the GA constructor.

**Comment by Erickson400** [comment]
yup that worked, i se the num_initial_links param to 2 and its not freezing. thanks
